version: "3"
services:
  sss:
    image: cppla/serverstatus:latest
    container_name: ServerStatus
    restart: unless-stopped
    volumes:
      - ./config.json:/ServerStatus/server/config.json 
      - ./json:/usr/share/nginx/html/json
    ports:
      - 35601:35601
      - 8081:80 
  bot:
    build:
      context: .
    container_name: ServerStatus_bot
    restart: unless-stopped
    environment:
      - TG_CHAT_ID=YOUR_TG_CHAT_ID
      - TG_BOT_TOKEN=YOUR_TG_BOT_TOKEN
