version: '2'

services:
  db:    # 数据库服务
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password  # 数据库root用户的密码，自行修改
      MYSQL_USER: your_filerun_username   # 数据库用户名，自行修改
      MYSQL_PASSWORD: your_filerun_password # 数据库密码，自行修改
      MYSQL_DATABASE: your_filerun_database #数据库名，自行修改
    volumes:
      - /root/data/docker_data/FileRun/filerun/db:/var/lib/mysql  # 挂载路径，冒号左边可以自己修改成VPS本地的路径，冒号右边为Docker容器内部路径，不能修改
    restart: always

  web:  # 网页服务
    image: filerun/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_filerun_database
      FR_DB_USER: your_filerun_username
      FR_DB_PASS: your_filerun_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db  # 两个容器互相连接
    ports:
      - "7444:80"  # Docker内部的80端口映射到VPS本地的8000端口，8000端口记得防火墙打开（宝塔、阿里云、腾讯云）
    volumes:
      - /root/data/docker_data/FileRun/filerun/html:/var/www/html  # 挂载路径，冒号左边可以自己修改成VPS本地的路径，冒号右边为Docker容器内部路径，不能修改
      - /root/data/docker_data/FileRun/filerun/user-files:/user-files  # 挂载路径，冒号左边可以自己修改成VPS本地的路径，冒号右边为Docker容器内部路径，不能修改
