version: '3'
services:
    easyimage:
        image: ddsderek/easyimage
        container_name: easyimage
        ports:
            - '7625:80'
        volumes:
            - '/root/data/docker_data/easyimage/config:/app/web/config'
            - '/root/data/docker_data/easyimage/i:/app/web/i'
        restart: unless-stopped
