version: '3.3'
services:
    xyfaka:
        image: ddsderek/xyfaka:latest
        restart: always
        container_name: xyfaka
        ports:
          - 8938:80
        volumes:
          - ./web:/app/web
        links:
          - mysql
        networks:
          - web
    mysql:
        image: mysql:5.7
        restart: always
        container_name: xyfaka-db
        environment:
          MYSQL_DATABASE: xyfaka
          MYSQL_USER: xyfaka
          MYSQL_PASSWORD: xyfaka
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        expose:
          - "3306"  # 不暴露公网，故没有写3306:3306
        volumes:
          - ./db:/var/lib/mysql
        networks:
            - web
networks:
  web:
    name: xyfaka
