version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /root/data/docker_data/duplicati/config:/config
      - /root/data/docker_data/duplicati/backups:/backups
      - /root/data:/source
    ports:
      - 7632:8200
    restart: unless-stopped
